[env:ttgo-t-sim7000g]
platform = espressif32
board = esp32dev
framework = arduino

monitor_speed = 115200
monitor_filters = esp32_exception_decoder

board_build.flash_mode = dio
board_build.flash_size = 16MB
board_build.partitions = default_16MB.csv
board_upload.flash_size = 16MB

build_flags =
    -D CORE_DEBUG_LEVEL=3
    -D TINY_GSM_MODEM_SIM7000

lib_deps =
    adafruit/Adafruit GFX Library
    adafruit/Adafruit SSD1306
    paulstoffregen/OneWire
    milesburton/DallasTemperature
    vshymanskyy/TinyGSM
    knolleary/PubSubClient
    bblanchon/ArduinoJson
    openslab-osu/SSLClient